### ISSUE TITLE
Terminology: stage/staging and live/production

### ISSUE THREAD

**Issue by alykat** [nprapps/interactive-template#6]
For consideration: The use of `stage` and `live` are a break from previous terminology we've used in our projects (`staging` and `production`). Granted, the team has largely turned over and this is a brand-new rig with different underlying technology. But I also feel like standardizing certain terms is helpful for both internal and external users as they get set up with our projects (across eras and tech stacks).

**Comment by thomaswilburn** [comment]
Was just going back over the issues and realizing that I think we've changed over enough stuff that my inadvertent terminology has become the norm. It was not my intent to filibuster this question! But given that that's the case, going to close it.
