### ISSUE TITLE
Does the OAuth token work for both sheets and docs?

### ISSUE THREAD

**Issue by benlk** [nprapps/interactive-template#7]
In `readme.rst`: 

> Access to Docs requires your machine to have a Google OAuth token, which is largely the same as described in [this post](http://blog.apps.npr.org/2015/03/02/app-template-oauth.html).

Earlier in that file:

> To configure your project for import, open the project.json file and add your workbook key to the sheets array found there. You'll also need to use the "Publish to Web" menu item in the Sheets UI (under file) to open up API access, or run `grunt google-auth` to create a local OAuth token.

So my questions are:
- Does the OAuth token from `grunt google-auth` work for Docs as well as Sheets, or only for Sheets?
- Does `grunt google-auth` require the configuration steps described in that blog post?

**Comment by thomaswilburn** [comment]
This does need to be communicated more clearly, I think:

* The OAuth token will be used for Sheets if it's provided, at which point you can access private workbooks and do not need to publish them to the web. If you don't have a token, you can still access workbooks that have gone through the "publish to the web" step.
* Docs always uses the token, I haven't tested it with public docs and no token. The access model is a little different between the two, unfortunately.
* It's all the same token, which is also used for Dailygraphics Next and our `google-login` NPM module.
* `google-auth` does require you to have an OAuth token set up using the same process as our other OAuth workflows, so the post should all still be relevant.

**Comment by benlk** [comment]
Thanks for clearing that up! I'll file a PR soon™ updating that chunk of the docs.
